site_name: pytest-vscode-integration
site_description: used to surface pytest functionality to ports for vscode integration
site_author: Eleanor Boyd

theme: readthedocs

repo_url: https://github.com/eleanorboyd/pytest-vscode-integration

pages:
- Home: index.md
